title: Ambrolla Photography
slogan: Treasure your moments
description: Washington DC, Maryland, and Virginia Photographer
author: 
  name: Ambrolla
  twitter: ambrolla

logo: "/assets/img/logo.jpg"

social-links:
  dribbble:
  email: contact@ambrolla.com
  facebook: ambrolla.photo
  flickr:
  github:
  instagram: ambrolla.photo
  linkedin:
  pinterest: ambrolla
  rss: # just type anything here for a working RSS icon
  twitter: ambrolla
  keybase:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

index_title: Portfolio

covers: /assets/img/covers/

social:
  name: Yuliya
  links:
    - https://twitter.com/ambrolla
    - https://www.facebook.com/ambrolla.photo
    - https://www.pinterest.com/ambrolla
    - https://instagram.com/ambrolla.photo

facebook:
  publisher: ambrolla.photo

twitter:
  username: ambrolla

google_analytics: UA-66941010-4

paginate: 5
paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->

url: https://ambrolla.com
baseurl: ""

future: true

collections:
  photo_categories:
    output: true
    permalink: /:path/:name/

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/meta_image.jpg"
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: photo_categories
    values:
      layout: category
      image_width: 1920
      image_height: 500
      cover: true

timezone: America/New_York
lang: en-US

plugins:
  - jekyll-seo-tag
#  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-remote-theme

sass:
  style: compressed

remote_theme: ambr0lla/jekyll-theme-modern

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
